### ISSUE TITLE
spawn a reconstruction directory

### ISSUE THREAD

**Issue by irischang020** [duaneloh/Dragonfly#13]
Hi,

I tried to do a quick simulation by typing
./dragonfly_init
in the topmost directory, following the instruction here https://github.com/duaneloh/Dragonfly/wiki/Quick-start-with-simulations, but got an error:
(dragonfly) [psanagpu104:Dragonfly]$ ./dragonfly_init
Traceback (most recent call last):
  File "./dragonfly_init", line 6, in <module>
    import init_new_recon
ImportError: No module named init_new_recon

Would you mind taking a look?

Thanks!

**Comment by kartikayyer** [comment]
I apologize, that wiki entry was out-of-date and has been updated. The workflow is now to compile using CMake and add the binaries to the path, which includes the `dragonfly_init` command. 

Then you go to a working directory (where you have plenty of space) and spawn the reconstruction directory.

Thanks for catching this. Let me know how it goes.

**Comment by irischang020** [comment]
@kartikayyer Thanks for the instruction. It's working now.
