### ISSUE TITLE
autoplot

### ISSUE THREAD

**Issue by irischang020** [duaneloh/Dragonfly#14]
Hi, I followed the instructions from the quick start guide and did the following:
```
./dragonfly_init 
cd recon_0004
./utils/sim_setup.py
./utils/run_emc.py
./utils/autoplot.py
```

A GUI popped up but it didn’t seem to work.
<img width="1433" alt="Screen Shot 2021-03-16 at 12 12 11 PM" src="https://user-images.githubusercontent.com/23045561/111366923-62068700-8651-11eb-97a4-a00709e1bf83.png">

And from the CLI, it said unable to open data.
```
(ana-4.0.17-py3) [psanagpu106:recon_0004]$ ./utils/autoplot.py     
Unable to open data//output/intens_001.bin
Unable to open data//output/intens_001.bin
```
Not sure if I've missed anything. 
Any advice would be appreciated!

**Comment by kartikayyer** [comment]
Hey, sorry for the late reply. 

Just click 'Check' to grab the appropriate data according to the config and log files.
