### ISSUE TITLE
Should priv_sum be initialized before using?

### ISSUE THREAD

**Issue by szsdk** [duaneloh/Dragonfly#8]
https://github.com/duaneloh/Dragonfly/blob/64a3d9f30506cdc298ff88396182a71fcc9380c7/src/max_emc.c#L241

**Comment by kartikayyer** [comment]
This has been fixed and will be in the next version.

**Comment by kartikayyer** [comment]
Fixed in v1.1.1
https://github.com/duaneloh/Dragonfly/blob/863a3e0ac5a1fe43feaf6f0ecd152f082209a91d/src/max_emc.c#L375
